### GET REQUEST
GET http://localhost:3000/post

### POST REQUEST
POST http://localhost:3000/post
Content-Type: application/json

{
    "band": "BBB King",
    "venue": "Unknown",
    "city": "San Francisco",
    "state": "California",
    "date": "03/03/2003",
    "desc": "test",
    "imgurl": "",
    "author": "test"
  }

### PUT REQUEST
PUT http://localhost:3000/post/64413624fe77bad1fee4755b
Content-Type: application/json

{
    "band": "BBB King",
    "venue": "Unknown",
    "city": "San",
    "state": "California",
    "date": "03/03/2003",
    "desc": "test",
    "imgurl": "",
    "author": "test"
  }

### DELETE REQUEST
DELETE http://localhost:3000/post/64552ff8e154e5fe00f8e37b
